### ISSUE TITLE
Add a model

### ISSUE THREAD

**Issue by vishv843** [MSTC-DA-IICT/Data-Science-Machine-Learning#4]
Add a model to fit the data. Training accuracy should be greater than 95% and testing accuracy should be greater than 85%.

**Comment by patenvy1234** [comment]
do we have to build our model using ML classification algo's like SVM,random_forest or we can use deep learning keras model like CNN

**Comment by vishv843** [comment]
> do we have to build our model using ML classification algo's like SVM,random_forest or we can use deep learning keras model like CNN

Use any model you wish and get the best possible result

**Comment by shoaib6174** [comment]
Hello,
I am also willing to contribute to this issue. Would you please assign this issue to me too?

**Comment by vishv843** [comment]
I will merge the solution whose algorithm gives a better result
