### ISSUE TITLE
Add explanation

### ISSUE THREAD

**Issue by vishv843** [MSTC-DA-IICT/Data-Science-Machine-Learning#6]
Add the reason in the notebook why flattening the data in this particular way is necessary and how exactly it is being flattened.

**Comment by patenvy1234** [comment]
Is this step to flatten the images necessary before building our model?

**Comment by patenvy1234** [comment]
As I am building a CNN network and I see no need why I have to flatten the data before building the model

**Comment by patenvy1234** [comment]
Is the step of flattening the data is necessary before building our model?

**Comment by patenvy1234** [comment]
As i am using CNN i don't see any reason to flatten the input data.

**Comment by vishv843** [comment]
Normalizing the input helps the optimization algorithm to converge faster and in general leads to better results. So that's why it is needed. You can even add batch normalization to make it even faster
